# Generated by Django 4.1 on 2022-09-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['title'], 'verbose_name': 'Настроение', 'verbose_name_plural': 'Настроения'},
        ),
        migrations.AlterField(
            model_name='mood',
            name='audio',
            field=models.FileField(upload_to='audios/%Y/%m/%d/', verbose_name='Компиляция'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='content',
            field=models.TextField(verbose_name='Создание настроения'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='size',
            field=models.TimeField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='style',
            field=models.CharField(max_length=50, verbose_name='Стилистика'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
