# Generated by Django 4.1 on 2022-09-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_category_mood_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='mood',
            name='style',
        ),
        migrations.AlterField(
            model_name='mood',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mood.category', verbose_name='Стилистика'),
        ),
    ]
