# Generated by Django 4.1 on 2022-09-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at'], 'verbose_name': 'Cтатья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
