# Generated by Django 4.1 on 2022-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Представление',
                'verbose_name_plural': 'Представления',
                'ordering': ['title'],
            },
        ),
    ]
